--liquibase formatted sql

-- ChangeSet nuwanw:1
CREATE TABLE job (
    JOB_DID BIGINT AUTO_INCREMENT PRIMARY KEY,
    JOB_NAME VARCHAR(100) NOT NULL,
    UUID VARCHAR(100) NOT NULL UNIQUE,
    IS_ENABLED BOOLEAN NOT NULL,
    CREATED_DATETIME DATETIME NOT NULL
);

-- ChangeSet nuwanw:3
CREATE TABLE network (
    NET_DID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DNS_SUFFIX VARCHAR(255),
    IP_ADDRESS VARCHAR(50) NOT NULL,
    SUBNET_MASK VARCHAR(50),
    DEFAULT_GATEWAY VARCHAR(50)
);
